/*Web Design & Development by: Jakub "Jacek" Bedynek | kuba.xray@gmail.com*/

export const TEXTS = {
	common: {
		storeLocation: "ul. Bieżuńska 1 lok. 51 03-578 Warszawa",
		open: "Pon-Pt 10:00 - 18:00",
		openService: "Pon-Pt 8:00 - 16:00",
		country: "Polska",
		location: "https://maps.app.goo.gl/s7hr6nTTHfrLKx3w6",
		onlineStoreLink: "https://www.ercomer.pl/",
		phoneMain: "+48 798 792 927",
		phoneSec: "",
		phoneService: "+48 733 473 173",
		email: "info@ercomer.com",
		phoneMainTitle: "Telefon sklepowy",
		phoneSecTitle: "Telefon komórkowy",
		phoneServiceTitle: "Telefon serwisowy",
		emailTitle: "Adres mailowy",
		storeTitle: "Sklep stacjonarny",
		onlineStore: "Sklep online",
		hoursTitle: "Sklep czynny",
		hoursService: "Serwis czynny",
		placeHolder: "Już niedługo",
	},

	nav: {
		brandName: "TYT-POLSKA",
		homeBtnP: "Niezawodna radiokomunikacja",
		navBtnProducts: "PRODUKTY",
		navBtnContact: "KONTAKT",
		navBtnBlog: "BLOG",
		categoryDMR: "DMR",
		categoryanalog: "ANALOGOWE",
		categoryPoc: "POC",
		categoryAccessories: "AKCESORIA",
	},

	footer: {
		titleStore: "Sklep Firmowy",
		contactTitle: "Kontakt",
		aboutTitle: "ERcomER",
		about: "Bezpośredni importer i autoryzowany dystrybutor oraz serwis radiotelefonów marki TYT. Prowadzimy sprzedaż radiotelefonów oraz oferujemy pełne wsparcie w zakresie wyboru sprzętu i projektowania oraz kompleksowego wdrożenia sieci radiokomunikacyjnych.",
	},

	main: {
		header: "NIEZAWODNE ROZWIĄZANIA RADIOKOMUNIKACYJNE",
		headerP:
			"Autoryzowany dystrybutor i serwis radiotelefonów marki TYT w Polsce",
		handmadeTitle: "Radiotelefony analogowe",
		handmadeText:
			"Pomimo dynamicznego rozwoju cyfrowych standardów łączności w ostatnim czasie, łączność analogowa jest powszechna i nadal będzie często wykorzystywana. W wielu przypadkach zapewnia niezawodną komunikację przy niższym koszcie urządzeń.",
		designTitle: "Radiotelefony cyfrowe DMR",
		designText:
			"DMR jest standardem cyfrowej łaczności radiowej umożliwiającym wydzielenie na  jednym kanale o szerokości 12,5kHz dwóch kanałów wirtualnych przez podział czasowy i umożliwiającym np. prowadzenie jednocześnie dwóch niezależnych rozmów.",
		effectivenessTitle: "Radiotelefony sieciowe PoC",
		effectiveness:
			"Rewolucja na rynku radiotelefonów. Radiotelefony sieciowe umożliwiają łączność z wykorzystaniem infrastruktury sieci komórkowej lub sieci bezprzewodowej WiFi. Dzięki takiemu medium, radiotelefony PoC umożliwiają łączność radiową w każdym miejscu na świecie, gdzie tylko zapewniony jest dostęp do sieci.",
		aboutTitle: "O TYT Electronics",
		aboutText:
			"TYT Electronics Co. Ltd. istnieje od ponad 20 lat i obecnie jest jednym z największych producentów sprzętu radiokomunikacyjnego posiadającym sieć sprzedaży dealerskiej na wszystkich kontynentach. TYT w przeciwieństwie do wielu konkurencyjnych marek obecnych aktualnie na rynku nie jest jedynie marką handlową, a producentem rozwijającym własne rozwiązania radiokomunikacyjne i posiadającym własne linie produkcyjne. Główną misją marki jest dostarczanie na rynek wysokiej jakości, niezawodne, a także nowoczesne i innowacyjne rozwiązania w zakresie sprzętu radiokomunikacyjnego, ale jednocześnie w bardzo konkurencyjnej cenie. Firma osiąga swój cel mniej inwestując w reklamę, ale dzięki ugruntowanej od lat renomie, bardzo dobrych opiniach i atrakcyjnej cenie produktów znana jest i ceniona na całym świecie. Obecnie TYT produkuje pełną linię radiotelefonów analogowych cyfrowych oraz sieciowych (PoC), a także retransmitery (repeatery) oraz akcesoria dedykowane zarówno dla użytkowników sieci profesjonalnych (wojsko, służby ratunkowe, grupy poszukiwawcze, ochrona, transport, zakłady produkcyjne, instytucje i firmy sektora prywatnego), jak również dla użytkowników indywidualnych (w tym radiotelefony nie wymagające zawolenia) oraz krótkofalowców, użytkowników pasmach amatorskich.",
	},

	contactSection: {
		form: "Przejdź do formularza",
		formLink: "https://www.ercomer.pl/pl/contact",
		formTitle: "Formularz kontaktowy",
	},

	breadcrumbs: {
		products: "Produkty",
		accessories: "Akcesoria",
		analog: "Analogowe",
		DMR: "DMR",
		poc: "POC",
		blog: "Blog",
		contact: "Kontakt",
	},

	blogSection: {
		header: "ARTYKUŁY",
		description: "",
		articles: [],
	},

	products: {
		common: {
			linkTitle: "Sklep",
			functionsTitle: "Funkcje",
			specTitle: "Specyfikacja techniczna",
		},

		DMR: {
			common: {
				title: "RADIOTELEFONY DMR",
				description:
					"DMR jest standardem cyfrowej łaczności radiowej umożliwiającym wydzielenie na  jednym kanale o szerokości 12,5kHz dwóch kanałów wirtualnych przez podział czasowy i umożliwiającym np. prowadzenie jednocześnie dwóch niezależnych rozmów. Radiotelefony DMR zapewniają wysoką jakość połączenia (bez szumów, zakłóceń itp.) oraz możliwość skutecznego szyfrowania łączności dla bezpieczeństwa naszych informacji.  Umożliwiają pracę zarówno w trybie rozmowy grupowej wielu osób (podobnie jak systemach analogowych), ale także tryb połączenia indywidualnego (Private Call, kiedy inni nie słyszą takiej rozmowy). Dla użytkowników dostępna jest też możliwość wymiany wiadomości tekstowych (SMS) drogą radiową, funkcje alarmowe i związane z zapewnieniem bezpieczeństwa,  lista kontaktów i zarządzanie użytkownikami, a nawet ich lokalizację GPS. Radiotelefony wyświetlają też ID lub nazwy użytkowów dla identyfikacji aktualnego rozmówcy. Ponadto standard DMR pozwala na  dłuższy czas pracy baterii radiotelefonu w stosunku do klasycznej łączności analogowej.",
			},
			md9600: {
				title: "MD-9600",
				description:
					"TYT MD-9600 to nowoczesny cyfrowy radiotelefon DMR do zastosowań mobilnych i stacjonarnych. Wykorzystuje on technologię TDMA i jest w pełni zgodny z standardem DMR ESTI TS 102 361-1, -2, -3 oraz jest kompatybilny z systemem MotoTRBO Tier I i II. MD-9600 charakteryzuje się dużą mocą wyjściową 50W (VHF) lub 45W (UHF) oraz solidną i wytrzymałą obudowę, spełniającą wymogi standardu militarnego MIL-STD-810C/D/E. Po za trybem cyfrowym DMR umożliwia łacznośc w trybie analogowym, dzięki czemu możliwe jest używanie w sieciach radiowych opartych na tradycyjnych rozwiązaniach. ",
				linkV1Title: "KUP MD-9600",
				linkV2Title: "KUP MD-9600 GPS",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-9600/1873",
				linkV2: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-9600-GPS/2011",
				functions: [
					"Wywołania indywidualne i grupowe",
					"Sygnalizacja ANI",
					"Szyfrowanie mowy",
					"Zdalne wyłączanie, włączanie i blokada radiotelefonu",
					"Obsługa wiadomości cyfrowych",
					"Książka kontaktów",
					"Programowalne przyciski funkcyjne",
					"Pełna obsługa tonów CTCSS i kodów DCS",
					"Blokowanie hasłem",
					"250 stref, do 16 kanałów na strefę",
					"1000 kanałów pamięci",
					"Duży, kolorowy wyświetlacz LCD",
					"Głosowe podpowiedzi nastaw",
					"Możliwość aktualizacji oprogramowania",
					"Funkcje alarmowe",
					"Skanowanie kanałów",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Odstęp międzykanałowy: 6.25/12.5/25kHz",
					"Napięcie zasilania: DC 13.8V",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Wymiary: 143x50x175mm",
					"Moc audio: 5W",
					"Moc wyjściowa: L: 25W H:50W (VHF) L: 25W H:45W (UHF)",
					"Czułość DMR: 0.30uV",
					"Czułość FM: 0.22uV",
					"Modulacja: 4FSK: 7K60FXD/7K60FXE FM: 11KOF3E/16KOF3E",
					"Vocoder: AMBE++",
				],
			},

			md750: {
				title: "MD-750",
				description:
					"MD-750 to przenośny duobander przeznaczony do pracy w pasmach VHF i UHF z mocą 5W. Pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-750 ułatwi w przyszłości migracje z systemu analogowego na cyfrowy. ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach VHF i UHF. Czytelny wyświetlacz LCD może pracować w trybie VFO, jak również w trybie kanałowym. Model ten zapewnia także możliwość odbioru pasma radiowego UKF FM i możliwość pracy w trybie Dual Watch. Posiada wbudowaną latarkę diodową. Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest wyjątkowo czysty i zrozumiały",
				linkV1Title: "KUP MD-750",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-750/3231",
				functions: [
					"Tryb pracy analogowy oraz cyfrowy DMR 2 slot",
					"Czytelny wyświetlacz",
					"Rozbudowane menu",
					"Możliwość pracy w Tier I, oraz Tier II",
					"Automatyczna funkcja oszczędzania energii",
					"Dual Band VHF+UHF, funkcja Dual watch",
					"1024 kanałów w pamięci",
					"Tony CTCSS i DCS tryb normal i invert",
					"Praca z shiftem (dla przemienników)",
					"Krok 5, 6.25, 10, 12.5, 25 kHz",
					"Wbudowane radio FM",
					"Blokada klawiatury",
					"Możliwość programowania z klawiatury lub z komputera",
					"Wbudowana funkcja latarki",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-520MHz",
					"Moc wyjściowa: 5W/1W",
					"Ilość kanałów: 1024",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
				],
			},

			md790: {
				title: "MD-790",
				description:
					"Ręczny radiotelefon TYT MD-790 pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-790 ułatwi w przyszłości migracje z systemu analogowemu na cyfrowy. Nadajnik o standardowej pełnej mocy 5W. Akumulator o pojemność 2800 mAh ładowany może być za pomocą ładowarki lub przez port USB-C. Umożliwia pracę na łącznie 64 kanałach (16 kanałów w 4 strefach). MD-790 zapewnia bardzo korzystną relację jakości i możliwości do ceny.",
				linkV1Title: "KUP MD-790",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-MD-790-UHF/3653",
				functions: [
					"Obsługa tonów CTCSS/DCS ",
					"Możliwość zaprogramowania funkcji przycisków",
					"Głosowe informacja dot. funkcji",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Możliwość aktualizowania oprogramowania radia",
					"Ilość kanałów 64 (16 kanałów w 4 strefach)",
					"Funkcja Lone Worker",
					"Pojemność akumulatora 2800 mAh ładowany za pomocą ładowarki lub przez port USB-C",
					"Programowanie za pośrednictwem komputera PC",
					"Możliwość pracy w trybie cyfrowym lub analogowym",
					"Możliwość zmiany poziomu mocy wyjściowej 5W/1W",
				],
				spec: [
					"Zakres częstotliwości: UHF: 400-470MHz",
					"Moc wyjściowa max: 5W",
					"Ilość kanałów: 64",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - +60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
					"Wymiary: 133x61x34mm",
					"Waga: 209g",
				],
			},

			md380: {
				title: "MD-UV380",
				description:
					"MD-UV380 to przenośny duobander przeznaczony do pracy w pasmach VHF i UHF z mocą 5W. Pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-UV380 ułatwi w przyszłości migracje z systemu analogowego na cyfrowy. Ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach VHF i UHF. Czytelny dwuwierszowy kolorowy wyświetlacz LCD ułatwia korzystanie z rozbudowanych funkcjonalności radiotelefonu. Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest wyjątkowo czysty i zrozumiały.",
				linkV1Title: "KUP MD-UV380",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-UV380-SP-DMR/2158",
				functions: [
					"Obsługa wiadomości tekstowych",
					"Wywołania indywidualne, grupowe, awaryjne",
					"Zdalny monitoring radia",
					"Funkcja samotnego pracownika",
					"Możliwość zdalnego wyłączania i blokowania radia",
					"Zaawansowane funkcje szyfrowania ",
					"Możliwość pracy w trybie cyfrowym lub analogowym",
					"Obsługa tonów CTCSS/DCS",
					"Kodowanie i dekodowanie DTMF",
					"Głosowe zapowiedzi",
					"Skanowanie",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Kompatybilność z MotoTRBO Tier I i II",
					"Możliwość aktualizowania oprogramowania radia",
					"3000 komórek pamięci",
					"Książka adresowa na 10.000 kontaktów",
					"Możliwość rejestracji transmisji",
					"Podwójny odbiornik A/B",
					"2 programowalne przyciski funkcyjne",
					"Rejestracja transmisji DMR w pamięci radia",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Moc wyjściowa: 5W/1W",
					"Ilość kanałów: 3000",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
				],
			},
			md390: {
				title: "MD-UV390 GPS",
				description:
					"MD-UV390 to przenośny, w pełni wodoszczelny z normą IP67 duobander przeznaczony do pracy w pasmach VHF i UHF z mocą 5W. Pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-UV380 ułatwi w przyszłości migracje z systemu analogowego na cyfrowy. Ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach VHF i UHF. Czytelny dwuwierszowy kolorowy wyświetlacz LCD ułatwia korzystanie z rozbudowanych funkcjonalności radiotelefonu. Model ten ma wbudowany moduł GPS. Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest wyjątkowo czysty i zrozumiały.",
				linkV1Title: "KUP MD-UV390 GPS",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-UV390-IP67-GPS-SP-DMR/3256",
				functions: [
					"Obsługa wiadomości tekstowych",
					"Wywołania indywidualne, grupowe, awaryjne",
					"Zdalny monitoring radia",
					"Funkcja samotnego pracownika",
					"Możliwość zdalnego wyłączania i blokowania radia",
					"Zaawansowane funkcje szyfrowania ",
					"Możliwość pracy w trybie cyfrowym lub analogowym",
					"Obsługa tonów CTCSS/DCS",
					"Kodowanie i dekodowanie DTMF",
					"Głosowe zapowiedzi",
					"Skanowanie",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Kompatybilność z MotoTRBO Tier I i II",
					"Możliwość aktualizowania oprogramowania radia",
					"3000 komórek pamięci",
					"Książka adresowa na 10.000 kontaktów",
					"Możliwość rejestracji transmisji",
					"Podwójny odbiornik A/B",
					"2 programowalne przyciski funkcyjne",
					"Rejestracja transmisji DMR w pamięci radia",
					"Wbudowany GPS (możliwość wykorzystania do systemu APRS via DMR)",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Moc wyjściowa: 5W/1W",
					"Ilość kanałów: 3000",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
				],
			},

			md390p: {
				title: "MD-UV390 PLUS GPS",
				description:
					"MD-UV390 to przenośny, w pełni wodoszczelny z normą IP67 duobander przeznaczony do pracy w pasmach VHF i UHF z dużą mocą nadajnika 10W. Pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-UV380 ułatwi w przyszłości migracje z systemu analogowego na cyfrowy. Ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach VHF i UHF. Czytelny dwuwierszowy kolorowy wyświetlacz LCD ułatwia korzystanie z rozbudowanych funkcjonalności radiotelefonu. Model ten ma wbudowany moduł GPS. Posiada wyjątkowo duży akumulator o pojemności 3600mAh, z możliwością ładowania przez port USB-C. W trybie szyfrowania obsługuje także ARC4, co powoduje że jest w pełni kompatybilny ze standardowym szyfrowaniem używanym w radiotelefonach marki Motorola. Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest wyjątkowo czysty i zrozumiały.",
				linkV1Title: "KUP MD-UV390 PLUS GPS",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-MD-UV390-GPS-PLUS-IP67-10W-ARC4-PRO/3625",
				functions: [
					"Obsługa wiadomości tekstowych",
					"Wywołania indywidualne, grupowe, awaryjne",
					"Zdalny monitoring radia",
					"Funkcja samotnego pracownika",
					"Możliwość zdalnego wyłączania i blokowania radia",
					"Zaawansowane funkcje szyfrowania, w tym kompatybilny z szyfrowaniem Motoroli tryb ARC4!",
					"Możliwość pracy w trybie cyfrowym DMR (kompatybilne m.in.z Motorolą) lub konwencjonalnym analogowym",
					"Obsługa tonów CTCSS/DCS",
					"Kodowanie i dekodowanie DTMF",
					"Głosowe zapowiedzi",
					"Skanowanie",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Kompatybilność z MotoTRBO Tier I i II",
					"Możliwość aktualizowania oprogramowania radia",
					"3000 komórek pamięci",
					"Książka adresowa na 10.000 kontaktów",
					"Możliwość rejestracji transmisji",
					"Podwójny odbiornik A/B",
					"2 programowalne przyciski funkcyjne",
					"Rejestracja transmisji DMR w pamięci radia",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Moc wyjściowa: max 10W",
					"Ilość kanałów: 3000",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
				],
			},

			md680: {
				title: "MD-680",
				description:
					"Ręczny radiotelefon TYT MD-680 pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-680 ułatwi w przyszłości migracje z systemu analogowemu na cyfrowy. MD-680 posiada bardzo wytrzymałą i wodoodporną obudowę spełniającą normę IP67, dzięki czemu radiotelefon wytrzymuje zanurzenie w wodzie do 30 minut na głębokość 1m. Wysoka moc nadajnika 10W zapewnia większy zasięg radiotelefonu w stosunku do konkurencyjnych modeli z tego segmentu.",
				linkV1Title: "KUP MD-680 VHF",
				linkV2Title: "KUP MD-680 UHF",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-MD-680-Dual-10W-IP67-VHF/2058",
				linkV2: "https://www.ercomer.pl/pl/p/TYT-MD-680-Dual-10W-IP67-UHF/2007",
				functions: [
					"Obsługa tonów CTCSS/DCS ",
					"Możliwość zaprogramowania funkcji przycisków",
					"Głosowe informacja dot. funkcji",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Możliwość aktualizowania oprogramowania radia",
					"Ilość kanałów: 16",
					"Programowanie za pośrednictwem komputera PC",
					"Możliwość pracy w trybie cyfrowym lub analogowym",
				],
				spec: [
					"Zakres częstotliwości (model VHF): 136-174MHz",
					"Zakres częstotliwości (model UHF): 400-480MHz",
					"Moc wyjściowa max: 10W",
					"Ilość kanałów: 16",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
					"Wymiary: 128x61x38mm",
					"Waga: 258g",
				],
			},
		},

		analog: {
			common: {
				title: "RADIOTELEFONY ANALOGOWE",
				description:
					"Pomimo dynamicznego rozwoju cyfrowych standardów łączności w ostatnim czasie, łączność analogowa jest powszechna i nadal będzie często wykorzystywana. W wielu przypadkach zapewnia niezawodną komunikację przy niższym koszcie urządzeń. Urządzenia marki TYT z tej grupy wyróżniają się na rynku nowoczesnym designem, bardzo dobrymi parametrami nadawczo-odbiorczymi i czystym sygnałem transmisji. Część modeli ma akumulatory o największej spotykanej na rynku pojemności, aż do 3600 mAh! Będzie to z pewnością bardzo istotny parametr dla wielu użytkowników przy wyborze radiotelefonów. Poszczególne modele różnią się głównie wielkością, mocą wyjściową i pojemnością akumulatora. Dstępne są modele jednopasmowe VHF lub UHF oraz modele dualband VHF+UHF. Wszystkie z nich mają z reguły ponad przeciętną funkcjonalność wśród konkurencyjnych modeli dostępnych na rynku.",
			},

			th9000d: {
				title: "TH-9000D",
				description:
					"TH-9000D to mobilny jedno zakresowy radiotelefon przewoźny dużej mocy (model VHF: 60W, model UHF: 45W). TH-9000D to radiotelefon pracujący w konwencjonalnym trybie analogowym. Dostępna jest zarówno wersja na pasmo VHF, jak również pasmo UHF. Czytelny, podświetlany wyświetlacz zapewnia wygodną obsługę. Niewielkie rozmiary pozwalają na instalację radiotelefonu TH-9000D w samochodach oraz jako urządzenie stacjonarne. Radiotelefon ma szereg przydatnych funkcji jak np. Scrambler, Compander wyśwtlanie identyfikatora w trybie ANI-ID, skanowanie, obsługę tonów (w tym tryby 2-Tone i 5-Tone), zmiana poziomu mocy nadajnika oraz wiele innych. Umożliwia także zarówno pracę w trybie VFO (częstotliwości), jak również w trybie zaprogramowanych pamięci (wyświetla numer kanału). Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest czysty i zrozumiały.",
				linkV1Title: "KUP TH-9000D VHF",
				linkV2Title: "KUP TH-9000D UHF",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TH-9000D-VHF/1484",
				linkV2: "https://www.ercomer.pl/pl/p/TYT-TH-9000D-UHF/1485",
				functions: [
					"Obsługa tonów CTCSS/DCS/1750Hz/DTMF/2-Tone/5-Tone",
					"Głosowe zapowiedzi",
					"Skanowanie i skanowanie priorytetowe",
					"Skanowanie tonów CTCSS/DCS",
					"Trzy poziomy mocy",
					"Praca przez przemienniki",
					"200 komórek pamięci",
					"Zdalne blokowanie/odblokowywanie radia",
					"Scrambler (opcjonalnie)",
					"Compander",
					"Tryb ANI ID",
					"Opis alfanumeryczny komórek pamięci",
					"Tryb VFO i tryb pamięci",
					"Odbiornik radia FM",
				],
				spec: [
					"Zakres częstotliwości (model VHF):  RX: 136-174MHz TX: 136-174MHz",
					"Zakres częstotliwości (model UHF): RX: 400-480MHz TX: 400-480MHz",
					"Moc wyjściowa (model VHF): 10W/25W/60W",
					"Moc wyjściowa  (model UHF): 10W/25W/45W",
					"Ilość kanałów: 200",
					"Odstęp międzykanałowy: 5/6.25/12.5/20/25/50kHz",
					"Napięcie robocze: 13.8V",
					"Impedancja anteny: 50Ω",
				],
			},
			th8600: {
				title: "TH-8600",
				description:
					"TH-8600 to niewielki mobilny duobander przeznaczony do pracy w pasmach VHF i UHF z mocą 25W/20W. TH-8600 to radiotelefon pracujący w konwencjonalnym trybie analogowym. TH-8600 ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach. Czytelny, podświetlany wyświetlacz zapewnia wygodną obsługę. Niewielkie rozmiary pozwalają na instalację radiotelefonu TH-9000D w samochodach oraz jako urządzenie stacjonarne. Radiotelefon dostępny jest zarówno w wersji standardowej, jak i wodoszczelnej (IP67). Wysokiej jakości wbudowany głośnik powodują że dźwięk jest czysty i zrozumiały.",
				linkV1Title: "KUP TH-8600",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TH-8600-IP54/1847",
				functions: [
					"Wyświetlane dwa VFO",
					"Kolorowy ekran LCD",
					"Zmiana koloru podświetlania",
					"Mikrofon z klawiaturą",
					"Niewielkie wymiary: 107x125x45",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-470MHz",
					"Ilość kanałów: 200",
					"Stabilność częstotliwości: +/-1.0ppm",
					"Zakres temperatur pracy: -30℃ - 60℃",
					"Napięcie zasilania: DC 13,8V",
					"Wymiar: 107*125*45mm",
					"Moc wyjściowa: 25W",
					"Czułość: 0.2μV",
					"Moc audio: 4W",
				],
			},
			tcf1: {
				title: "TC-F1",
				description:
					"Prosty i wytrzymały radiotelefon na pasmo UHF z pojemnym akumulatorem 2800mAh. TC-F1 to radiotelefon pracujący w konwencjonalnym trybie analogowym. Radiotelefon świetnie sprawdzi się w typowych zastosowaniach wymagających prostej, ale niezawodnej komunikacji. Odpowiedni kształt i teksturowana obudowa poprawia ergonomię chwytu. Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest wyjątkowo czysty i zrozumiały. W zestawie fabrycznym znajduje się ładowarka biurkowa. ",
				linkV1Title: "KUP TC-F1",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TC-F1/2249",
				functions: [
					"Moc wyjściowa 5W",
					"16 kanałów",
					"Pojemny akumulator Li-ION 2800mAh",
					"Złącze akcesoriów typu K",
					"Układ VOX",
					"Układ oszczędzania baterii",
				],
			},
			tc999: {
				title: "TC-999",
				description:
					"TYT TC-999 to analogowy radiotelefon przeznaczony do zastosowań profesjonalnych, pracujący w paśmie PMR446 nie wymagającym zezwolenia. Zapewnia bardzo dobre parametry nadawczo-odbiorcze, przewyższające konkurencyjne urządzenia w tej klasie. Możliwość ładowania akumulatora przez port USB jest także niezwykle wygodnym rozwiązaniem. Radiotelefon świetnie sprawdzi się w typowych zastosowaniach wymagających prostej, ale niezawodnej komunikacji. Odpowiedni kształt i teksturowana obudowa poprawia ergonomię chwytu. Wysokiej jakości wbudowany głośnik powoduje że dźwięk jest wyjątkowo czysty i zrozumiały. Maksymalna moc nadajnika w drodze serwisowej może zostać odblokowana do 2-2.5W (radiotelefon wówczas nie spełni już wymagań Ustawy dla pracy bez zezwolenia).",
				linkV1Title: "KUP TC-999",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TC-999-USB-C-PMR-446/3517",
				functions: [
					"Obsługa tonów CTCSS/DCS",
					"Głosowe zapowiedzi w j. angielskim",
					"Funkcja skanowania (scaner)",
					"16 kanałów (komórek pamięci)",
					"Funkcja VOX (automatyczne uruchamianie nadawania głosem)",
					"Scrambler (kodowanie mowy)",
					"Możliwość programowania z komputera",
				],
				spec: [
					"Zakres częstotliwości: (446.00625-446.09375MHz)",
					"Ilość kanałów: 16 ",
					"Akumulator 1200mAh (Li-ION) ładowany przez USB",
					"Moc wyjściowa audio 1W",
				],
			},
			thuv88: {
				title: "TH-UV88",
				description:
					"TH-UV88 to przenośny duobander przeznaczony do pracy w pasmach VHF i UHF z mocą 5W. TH-UV88 to radiotelefon pracujący w konwencjonalnym trybie analogowym. TH-UV88 ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach. Zapewnia również możliwość odbioru pasma radiowego UKF FM, funkcję skanowania kanałów, Dual Watch i posiada wbudowaną latarkę diodową. Czytelny, podświetlany dwuwierszowy wyświetlacz z matrycą punktową zapewnia wygodną obsługę. Wysokiej jakości wbudowany głośnik powodują że dźwięk jest czysty i zrozumiały. TH-UV88 zapewnia bardzo korzystną relację jakości i możliwości do ceny.",
				linkV1Title: "KUP TH-UV88",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TH-UV88-PRO/3383",
				functions: [
					"Podwójny odbiorniki VHF/UHF",
					"Obsługa tonów CTCSS/DCS",
					"200 komórek pamięci",
					"Radio FM",
					"Układ VOX",
					"Skaner częstotliwości",
					"Scrambler",
					"Ton 1750",
					"DTMF",
					"Dual Watch ",
					"Możliwość programowania kanałów i ustawień z poziomu PC",
					"Zmienny krok przestrajania, w tym m.in. 6,25kHz (dla pasma PMR446)",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHzS",
					"Moc wyjściowa: VHF: 5W/2W/0.5W UHF: 4W/2W/0.5W",
					"Ilość kanałów: 200",
					"Czułość: -122dBm",
					"Pobór prądu: TX: 1.6A",
					"Napięcie robocze: 7.4V",
					"Impedancja anteny: 50Ω",
					"Wymiary: 116 x 59 x 34 mm",
				],
			},
			thuv99: {
				title: "TH-UV99",
				description:
					"TH-UV99 to przenośny, w pełni wodoszczelny z normą IP68 duobander przeznaczony do pracy w pasmach VHF i UHF z dużą mocą nadajnika 10W. TH-UV88 to radiotelefon pracujący w konwencjonalnym trybie analogowym. TH-UV88 ma duże możliwości dostosowywania do potrzeb użytkownika dzięki pracy w obu pasmach. Możliwość ładowania akumulatora przez port USB-C w tym modelu jest także niezwykle wygodnym rozwiązaniem. Akumulator ma wyjątkowo dużą pojemność, aż 3600mAh. TH-UV99 zapewnia również możliwość odbioru pasma radiowego UKF FM, funkcję skanowania kanałów, Dual Watch i posiada wbudowaną latarkę diodową. Czytelny, podświetlany dwuwierszowy wyświetlacz z matrycą punktową zapewnia wygodną obsługę. Wysokiej jakości wbudowany głośnik powodują że dźwięk jest czysty i zrozumiały.",
				linkV1Title: "KUP TH-UV99",
				linkV1: "https://ercomerpl.shoparena.pl/pl_PL/p/TYT-TH-UV99-PRO-3600mAh/3629?preview=true",
				functions: [
					"Pasma VHF + UHF",
					"Obsługa tonów CTCSS/DCS/5Tone/2Tone",
					"200 komórek pamięci",
					"Redukcja szumów",
					"Układ VOX",
					"Skaner częstotliwości",
					"Scrambler",
					"Ton 1750",
					"DTMF",
					"Dual Watch - nasłuch dwóch kanałów",
					"Radio UKF FM 66-108MHz",
					"Możliwość programowania kanałów i ustawień z poziomu PC (opcja)",
					"Zmienny krok przestrajania, w tym m.in. 6,25kHz (dla pasma PMR446)",
					"Zmiana poziomu mocy 1W/5W/10W",
					"Bardzo duży akumulator - pojemność 3600mAh",
					"Multiładowarka: ładowarka biurkowa / ładowanie USB-C",
				],
			},
		},

		poc: {
			common: {
				title: "RADIOTELEFONY POC",
				description:
					"Rewolucja na rynku radiotelefonów. Radiotelefony sieciowe umożliwiają łączność z wykorzystaniem infrastruktury sieci komórkowej lub sieci bezprzewodowej WiFi. Dzięki takiemu medium, radiotelefony PoC umożliwiają łączność radiową w każdym miejscu na świecie, gdzie tylko zapewniony jest dostęp do sieci.Dla systemów PoC dostępne jest także oprogramowanie konsoli dyspozytorskiej - na komputer PC lub w wersji online. Dzięki niemu możesz zobaczyć pozycję użytkowników na mapie,  skutecznie zarządzać grupą osób i koordynować ich działania w terenie, zapisywać trasy, zarządzać łącznością. Doskonałe, nowoczesne i funkcjonalne rozwiązanie dla ochrony, służb, transportu, grup terenowych, ale także dużych zakładów przemysłowych, gdzie skutecznie rozwiązuje problemy z zasięgiem konwencjonalnych sieci radiowych.",
			},
			ip77: {
				title: "IP-77",
				description:
					"Radiotelefon TYT IP-77 z wyświetlaczem, umożliwia łączność z wykorzystaniem infrastruktury sieci komórkowej. Dzięki takiemu medium, radiotelefony sieciowe umożliwiają łączność radiową w każdym miejscu na świecie, gdzie zapewniony jest dostęp do sieci. Radiotelefony posiadają wytrzymałą i kompaktową konstrukcję. Radiotelefony do pracy wymagają wykupienia licencji miesięcznej/rocznej lub dożywotniej (obsługi serwera komunikacyjnego) - aczkolwiek koszt obsługi jest relatywnie niewielki.",
				linkV1Title: "KUP IP-77",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-IP-77/2813",
				functions: [
					"Łączność przez sieć komórkową WCDMA/CDMA/GSM/LTE ",
					"Android 5.1.1",
					"Bluetooth",
					"Łączność WiFi",
					"Kolorowy wyświetlacz LCD",
					"Wbudowany GPS",
					"Akumulator 4200mAh",
				],
			},
			ip79: {
				title: "IP-79",
				description:
					"IP-79 to hybrydowy radiotelefon umożliwiający pracę zarówno w trybie sieciowym POC, jak również w standardowym analogowym trybie konwencjonalnym w paśmie UHF. W paśmie UHF zapewnia pełną moc nadajnika 5W. Kompatybilny jest z każdym standardowym analogowym radiotelefonem pracującym w paśmie UHF, w tym również PMR446. Umożliwia łączność z jednoczesnym dostępem do infrastruktury sieci komórkowej i pracy analogowej UHF. W trybie sieciowym POC umożliwia łączność z wykorzystaniem infrastruktury sieci komórkowej. Dzięki takiemu medium, radiotelefony sieciowe umożliwiają łączność radiową w każdym miejscu na świecie, gdzie zapewniony jest dostęp do sieci. Radiotelefony posiadają wytrzymałą i kompaktową konstrukcję. Do pracy w trybie sieciowym radiotelefony wymagają wykupienia licencji miesięcznej/rocznej lub dożywotniej obsługi serwera komunikacyjnego - aczkolwiek koszt ich obsługi jest relatywnie niewielki.",
				linkV1Title: "KUP IP-79",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-IP-79-hybrydowy-PoC-LTE-oraz-UHF-4W/3200",
				functions: [
					"Łączność przez sieć komórkową WCDMA/CDMA/GSM/LTE",
					"Łączność analogową w paśmie UHF 400-470MHz",
					"Kolorowy wyświetlacz LCD",
					"Wbudowany GPS",
					"Dwa niezależne przyciski przycisk „PTT”",
				],
			},
			ip66: {
				title: "IP-66",
				description:
					"Radiotelefon TYT IP-66 umożliwia globalną łączność z wykorzystaniem infrastruktury sieci komórkowej. Dzięki takiemu medium, radiotelefony sieciowe umożliwiają łączność radiową w każdym miejscu na świecie, gdzie zapewniony jest dostęp do sieci. Radiotelefony posiadają wytrzymałą i kompaktową konstrukcję. Radiotelefony do pracy wymagają wykupienia licencji miesięcznej/rocznej lub dożywotniej (obsługi serwera komunikacyjnego) - aczkolwiek koszt obsługi jest relatywnie niewielki.",
				linkV1Title: "KUP IP-66",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-IP-66-Mandown/3467",
				functions: [
					"Łączność przez sieć komórkową WCDMA/CDMA/GSM/LTE ",
					"Android 8.1",
					"Bluetooth 4.2",
					"WiFi 2.4/5GHz IEEE 802.11 b/g/n",
					"Wyświetlacz LED",
					"Wbudowany GPS",
					"Programowanie OTA bezprzewodowe (over-the-air)",
					"Akumulator 5000mAh z ładowaniem przez port USB-C",
					"Aktywny układ redukcji szumów",
					"Funkcja Mandown",
					"Opcjonalnie funkcja NFC",
					"Mocny wbudowany głośnik 2000mW, 36mm",
					"Wzmocniona konstrukcja obudowy",
				],
			},
		},
	},
};
