/*Web Design & Development by: Jakub "Jacek" Bedynek | kuba.xray@gmail.com*/

export const TEXTS = {
	common: {
		storeLocation: "ul. Bieżuńska 1 lok. 51 03-578 Warszawa",
		open: "Pon-Pt 10:00 - 18:00",
		country: "Polska",
		location: "https://maps.app.goo.gl/s7hr6nTTHfrLKx3w6",
		onlineStoreLink: "https://www.ercomer.pl/",
		phoneMain: "(+48) 22 270 12 15",
		phoneSec: "(+48) 798 792 927",
		phoneService: "(+48) 22 270 12 07",
		email: "info@ercomer.com",
		phoneMainTitle: "Telefon główny",
		phoneSecTitle: "Telefon komórkowy",
		phoneServiceTitle: "Dział produkcji i serwisu",
		emailTitle: "Adres mailowy",
		storeTitle: "Sklep stacjonarny",
		onlineStore: "Sklep online",
		hoursTitle: "Godziny otwarcia",
		placeHolder: "Już niedługo",
	},

	nav: {
		brandName: "TYT POLSKA",
		homeBtnP: "Niezawodna radiokomunikacja",
		navBtnProducts: "PRODUKTY",
		navBtnContact: "KONTAKT",
		navBtnBlog: "BLOG",
		categoryProfessional: "PROFESJONALNE",
		categoryAmateur: "AMATORSKIE",
		categoryAccessories: "AKCESORIA",
	},

	footer: {
		titleStore: "Sklep Firmowy",
		contactTitle: "Kontakt",
		aboutTitle: "O TYT Polska",
		about: "TYT Polska jest marką handlową firmy ERcomER.",
	},

	main: {
		header: "",
		headerP: "",
		handmadeTitle: "",
		handmadeText: "",
		designTitle: "",
		designText: "",

		effectivenessTitle: "",

		effectiveness: "",
		aboutTitle: "",
		aboutText: "",
	},

	contactSection: {
		form: "Przejdź do formularza",
		formLink: "https://www.ercomer.pl/pl/contact",
		formTitle: "Formularz kontaktowy",
	},

	breadcrumbs: {
		products: "Produkty",
		accessories: "Akcesoria",
		wire: "Amatorskie",
		vertical: "Profejsonalne",
		blog: "Blog",
		about: "O nas",
		contact: "Kontakt",
	},

	blogSection: {
		header: "ARTYKUŁY",
		description: "",
		articles: [],
	},

	products: {
		common: {
			linkTitle: "Sklep",
			functionsTitle: "Funkcję",
			specTitle: "Specyfikacja techniczna",
		},

		professional: {
			common: {
				title: "RADIOTELEFONY PROFESJONALNE",
				description: "",
			},
			md9600: {
				title: "MD-9600",
				description:
					"TYT MD-9600 to nowoczesny cyfrowy radiotelefon DMR do zastosowań mobilnych i stacjonarnych. Wykorzystuje on technologię TDMA i jest w pełni zgodny z standardem DMR ESTI TS 102 361-1, -2, -3 oraz jest kompatybilny z systemem MotoTRBO Tier I i II. MD-9600 charakteryzuje się dużą mocą wyjściową 50W (VHF) lub 45W (UHF) oraz solidną i wytrzymałą obudowę, spełniającą wymogi standardu militarnego MIL-STD-810C/D/E. Po za trybem cyfrowym DMR umożliwia łacznośc w trybie analogowym, dzięki czemu możliwe jest używanie w sieciach radiowych opartych na tradycyjnych rozwiązaniach. ",
				linkV1Title: "BEZ GPS",
				linkV2Title: "GPS",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-9600/1873",
				linkV2: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-9600-GPS/2011",
				functions: [
					"Wywołania indywidualne i grupowe",
					"Sygnalizacja ANI",
					"Szyfrowanie mowy",
					"Zdalne wyłączanie, włączanie i blokada radiotelefonu",
					"Obsługa wiadomości cyfrowych",
					"Książka kontaktów",
					"Programowalne przyciski funkcyjne",
					"Pełna obsługa tonów CTCSS i kodów DCS",
					"Blokowanie hasłem",
					"250 stref, do 16 kanałów na strefę",
					"1000 kanałów pamięci",
					"Duży, kolorowy wyświetlacz LCD",
					"Głosowe podpowiedzi nastaw",
					"Możliwość aktualizacji oprogramowania",
					"Funkcje alarmowe",
					"Skanowanie kanałów",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Odstęp międzykanałowy: 6.25/12.5/25kHz",
					"Napięcie zasilania: DC 13.8V",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Wymiary: 143x50x175mm",
					"Moc audio: 5W",
					"Moc wyjściowa: L: 25W H:50W (VHF) L: 25W H:45W (UHF)",
					"Czułość DMR: 0.30uV",
					"Czułość FM: 0.22uV",
					"Modulacja: 4FSK: 7K60FXD/7K60FXE FM: 11KOF3E/16KOF3E",
					"Vocoder: AMBE++",
				],
			},
			th9000d: {
				title: "TH-9000D",
				description:
					"TH-9000D to mobilny jedno zakresowy radiotelefon przewoźny dużej mocy (model VHF: 60W, model UHF: 45W).",
				linkV1Title:
					"https://www.ercomer.pl/pl/p/TYT-TH-9000D-VHF/1484",
				linkV2Title:
					"https://www.ercomer.pl/pl/p/TYT-TH-9000D-UHF/1485",
				linkV1: "VHF",
				linkV2: "UHF",
				functions: [
					"Obsługa tonów CTCSS/DCS/1750Hz/DTMF/2-Tone/5-Tone",
					"Głosowe zapowiedzi",
					"Skanowanie i skanowanie priorytetowe",
					"Skanowanie tonów CTCSS/DCS",
					"Trzy poziomy mocy",
					"Praca przez przemienniki",
					"200 komórek pamięci",
					"Zdalne blokowanie/odblokowywanie radia",
					"Scrambler (opcjonalnie)",
					"Compander",
					"Tryb ANI ID",
					"Opis alfanumeryczny komórek pamięci",
					"Tryb VFO i tryb pamięci",
					"Odbiornik radia FM",
				],
				spec: [
					"Zakres częstotliwości (model VHF):  RX: 136-174MHz TX: 136-174MHz",
					"Zakres częstotliwości (model UHF): RX: 400-480MHz TX: 400-480MHz",
					"Moc wyjściowa (model VHF): 10W/25W/60W",
					"Moc wyjściowa  (model UHF): 10W/25W/45W",
					"Ilość kanałów: 200",
					"Odstęp międzykanałowy: 5/6.25/12.5/20/25/50kHz",
					"Napięcie robocze: 13.8V",
					"Impedancja anteny: 50Ω",
				],
			},
			tcf1: {
				title: "TC-F1 ",
				description:
					"Prosty i wytrzymały radiotelefon na pasmo 70cm z pojemnym akumulatorem 2800mAh.",
				linkV1Title: "Sklep",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TC-F1/2249",
				functions: [
					"Moc wyjściowa 5W",
					"16 kanałów",
					"Pojemny akumulator Li-ION 2800mAh",
					"Złącze akcesoriów typu K",
					"Układ VOX",
					"Układ oszczędzania baterii",
				],
			},
			tc999: {
				title: "TC-999",
				description:
					"TYT TC-999 na pasmo PMR446 to analogowy radiotelefon przeznaczony do zastosowań profesjonalnych, pracujący w paśmie PMR446 nie wymagającym zezwolenia. Najnowsza wersja produkcyjna - nowy firmware i możliwość ładowania akumulatora przez port USB-C! (Po modyfikacji software nadajnik osiąga moc 2W).",
				linkV1Title: "Sklep",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-TC-999-USB-C-PMR-446/3517",
				functions: [
					"Obsługa tonów CTCSS/DCS",
					"Głosowe zapowiedzi w j. angielskim",
					"Funkcja skanowania (scaner)",
					"16 kanałów (komórek pamięci)",
					"Funkcja VOX (automatyczne uruchamianie nadawania głosem)",
					"Scrambler (kodowanie mowy)",
					"Możliwość programowania z komputera",
				],
				spec: [
					"Zakres częstotliwości: (446.00625-446.09375MHz)",
					"Ilość kanałów: 16 ",
					"Akumulator 1200mAh (Li-ION) ładowany przez USB-C",
					"Moc wyjściowa audio 1W",
				],
			},
			md680: {
				title: "MD-680",
				description:
					"Ręczny radiotelefon TYT MD-680 pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II (pracuje z wykorzystaniem obu slotów). Dzięki możliwości pracy również w trybie analogowym, zastosowanie radiotelefonu MD-680 ułatwi w przyszłości migracje z systemu analogowemu na cyfrowy. MD-680 posiada wodoodporną obudowę spełniającą normę IP67, dzięki czemu radiotelefon wytrzymuje zanurzenie w wodzie do 30 minut na głębokość 1m.",
				linkV1Title: "VHF",
				linkV2Title: "UHF",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-MD-680-Dual-10W-IP67-VHF/2058",
				linkV2: "https://www.ercomer.pl/pl/p/TYT-MD-680-Dual-10W-IP67-UHF/2007",
				functions: [
					"Obsługa tonów CTCSS/DCS ",
					"Możliwość zaprogramowania funkcji przycisków",
					"Głosowe informacja dot. funkcji",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Możliwość aktualizowania oprogramowania radia",
					"Ilość kanałów: 16",
					"Programowanie za pośrednictwem komputera PC",
					"Możliwość pracy w trybie cyfrowym lub analogowym",
				],
				spec: [
					"Zakres częstotliwości (model VHF): 136-174MHz",
					"Zakres częstotliwości (model UHF): 400-480MHz",
					"Moc wyjściowa max: 10W",
					"Ilość kanałów: 16",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
					"Wymiary: 128x61x38mm",
					"Waga: 258g",
				],
			},
			md390p: {
				title: "MD-UV390 PLUS",
				description:
					"Profesjonalny, wodoszczelny IP67, dwu zakresowy cyfrowy radiotelefon TYT MD-UV390 PLUS, pracujący w standardzie cyfrowym DMR oraz w standardowym trybie analogowym w pełnym zakresie pasm VHF i UHF. Akumulator 3600mAh ładowany przez USB-C! Nadajnik dużej mocy 10W! Kompatybilny z szyfrowaniem Motoroli ARC4!",
				linkV1Title: "Sklep",
				linkV1: "https://www.ercomer.pl/pl/p/TYT-MD-UV390-PLUS-IP67-10W-ARC4-PRO/3516",
				functions: [
					"Obsługa wiadomości tekstowych",
					"Wywołania indywidualne, grupowe, awaryjne",
					"Zdalny monitoring radia",
					"Funkcja samotnego pracownika",
					"Możliwość zdalnego wyłączania i blokowania radia",
					"Zaawansowane funkcje szyfrowania, w tym kompatybilny z szyfrowaniem Motoroli tryb ARC4!",
					"Możliwość pracy w trybie cyfrowym DMR (kompatybilne m.in.z Motorolą) lub konwencjonalnym analogowym",
					"Obsługa tonów CTCSS/DCS",
					"Kodowanie i dekodowanie DTMF",
					"Głosowe zapowiedzi",
					"Skanowanie",
					"Zgodność z protokołem ESTI TS 102 361-1, -2, -3",
					"Kompatybilność z MotoTRBO Tier I i II",
					"Możliwość aktualizowania oprogramowania radia",
					"3000 komórek pamięci",
					"Książka adresowa na 10.000 kontaktów",
					"Możliwość rejestracji transmisji",
					"Podwójny odbiornik A/B",
					"2 programowalne przyciski funkcyjne",
					"Rejestracja transmisji DMR w pamięci radia",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Moc wyjściowa: max 10W",
					"Ilość kanałów: 3000",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
				],
			},
			md750: {
				title: "MD-750",
				description:
					"Ręczny radiotelefon TYT MD-750 pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II.",
				linkV1Title: "Sklep",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-750/3231",
				functions: [
					"Tryb pracy analogowy oraz cyfrowy DMR 2 slot",
					"Czytelny wyświetlacz",
					"Rozbudowane menu",
					"Możliwość pracy w Tier I, oraz Tier II",
					"Automatyczna funkcja oszczędzania energii",
					"Dual Band VHF+UHF, funkcja Dual watch",
					"1024 kanałów w pamięci",
					"Tony CTCSS i DCS tryb normal i invert",
					"Praca z shiftem (dla przemienników)",
					"Krok 5, 6.25, 10, 12.5, 25 kHz",
					"Wbudowane radio FM",
					"Blokada klawiatury",
					"Możliwość programowania z klawiatury lub z komputera",
					"Wbudowana funkcja latarki",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-520MHz",
					"Moc wyjściowa: 5W/1W",
					"Ilość kanałów: 1024",
					"Odstęp międzykanałowy: 12.5kHz",
					"Napięcie robocze: 7.4V",
					"Stabilność częstotliwości: +/- 1.0ppm",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Moc wyjściowa audio: 1000mW",
				],
			},
			md790: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
		},

		amateur: {
			common: {
				title: "RADIOTELEFONY AMATORSKIE",
				description: "",
			},
			md9600: {
				title: "MD-9600",
				description:
					"TYT MD-9600 to nowoczesny cyfrowy radiotelefon DMR do zastosowań mobilnych i stacjonarnych. Wykorzystuje on technologię TDMA i jest w pełni zgodny z standardem DMR ESTI TS 102 361-1, -2, -3 oraz jest kompatybilny z systemem MotoTRBO Tier I i II. MD-9600 charakteryzuje się dużą mocą wyjściową 50W (VHF) lub 45W (UHF) oraz solidną i wytrzymałą obudowę, spełniającą wymogi standardu militarnego MIL-STD-810C/D/E. Po za trybem cyfrowym DMR umożliwia łacznośc w trybie analogowym, dzięki czemu możliwe jest używanie w sieciach radiowych opartych na tradycyjnych rozwiązaniach. ",
				linkV1Title: "BEZ GPS",
				linkV2Title: "GPS",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-9600/1873",
				linkV2: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-9600-GPS/2011",
				functions: [
					"Wywołania indywidualne i grupowe",
					"Sygnalizacja ANI",
					"Szyfrowanie mowy",
					"Zdalne wyłączanie, włączanie i blokada radiotelefonu",
					"Obsługa wiadomości cyfrowych",
					"Książka kontaktów",
					"Programowalne przyciski funkcyjne",
					"Pełna obsługa tonów CTCSS i kodów DCS",
					"Blokowanie hasłem",
					"250 stref, do 16 kanałów na strefę",
					"1000 kanałów pamięci",
					"Duży, kolorowy wyświetlacz LCD",
					"Głosowe podpowiedzi nastaw",
					"Możliwość aktualizacji oprogramowania",
					"Funkcje alarmowe",
					"Skanowanie kanałów",
				],
				spec: [
					"Zakres częstotliwości: VHF: 136-174MHz UHF: 400-480MHz",
					"Odstęp międzykanałowy: 6.25/12.5/25kHz",
					"Napięcie zasilania: DC 13.8V",
					"Zakres temperatur pracy: -30°C - 60°C",
					"Impedancja anteny: 50Ω",
					"Wymiary: 143x50x175mm",
					"Moc audio: 5W",
					"Moc wyjściowa: L: 25W H:50W (VHF) L: 25W H:45W (UHF)",
					"Czułość DMR: 0.30uV",
					"Czułość FM: 0.22uV",
					"Modulacja: 4FSK: 7K60FXD/7K60FXE FM: 11KOF3E/16KOF3E",
					"Vocoder: AMBE++",
				],
			},
			th8600: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
			thuv88: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
			thuv99: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
			md750: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
			md380: {
				title: "MD-UV380",
				description:
					"Ręczny radiotelefon TYT MD-UV380 pracuje w trybie cyfrowym wykorzystującym technologię TDMA i jest w pełni zgodny ze standardem DMR, kompatybilny z MotoTRBO Tier I i II.",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "https://www.ercomer.pl/pl/p/Duobander-TYT-MD-UV380-SP-DMR/2158",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
			md390: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
			md390p: {
				title: "",
				description: "",
				linkV1Title: "",
				linkV2Title: "",
				linkV1: "",
				linkV2: "",
				functions: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
				spec: [
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
				],
			},
		},

		accessories: {
			common: {
				title: "AKCESORIA",
				description: "",
			},
		},
	},
};
